using UnityEngine;

/// <summary>
/// Soft hockey-net catch for the 1v1 test scene. Goes on the back / side / top netting
/// trigger volumes generated by <c>TestNetSetup</c>. The frame (posts + crossbar) is solid
/// so the puck dings off the iron; the netting is a TRIGGER with this script so it CATCHES
/// the puck — kills most of its speed on entry and bleeds the rest to a near-stop while it
/// sits inside — instead of rebounding it like a wall.
///
/// This is the reason the real net does not need <c>TestGoalTrigger.netDeadenFactor</c>'s
/// hack: the imported arena goal mesh's blanket MeshCollider (which made the whole net solid
/// and pinged hard shots back out) is disabled, and this gives the netting its softness.
///
/// Test-scene port of <c>Goals/NetPhysics.cs</c> (same catch math, puck-tag gated).
/// </summary>
[RequireComponent(typeof(Collider))]
public class TestNetDeaden : MonoBehaviour
{
    [Tooltip("Fraction of speed killed the instant the puck enters the netting (0-1, 1 = full stop). " +
             "0.5 = keep half, so a hard shot blasts INTO the net and rattles against the back / " +
             "backstop a couple times before settling, instead of dead-stopping the moment it touches " +
             "the netting. Raise toward 0.9 if pucks punch out the back; lower for more rattle.")]
    [Range(0f, 1f)]
    public float velocityReduction = 0.5f;

    [Tooltip("How fast (m/s per second) the puck is bled down to maxSpeedInNet, then to rest, " +
             "while it stays inside the netting.")]
    [Range(0f, 50f)]
    public float slowdownRate = 15f;

    [Tooltip("Speed the puck is allowed to keep while in the net before it's slowed to a stop.")]
    [Range(0f, 3f)]
    public float maxSpeedInNet = 0.5f;

    private void Awake()
    {
        GetComponent<Collider>().isTrigger = true;
    }

    private void OnTriggerEnter(Collider other)
    {
        if (!other.CompareTag("Puck")) return;
        Rigidbody puckRb = other.attachedRigidbody;
        if (puckRb == null) return;

        // Dump most of the speed the moment it hits the netting so it doesn't blow through.
        puckRb.linearVelocity *= (1f - velocityReduction);
    }

    private void OnTriggerStay(Collider other)
    {
        if (!other.CompareTag("Puck")) return;
        Rigidbody puckRb = other.attachedRigidbody;
        if (puckRb == null) return;

        // Bleed whatever speed is left toward maxSpeedInNet, then down to a dead stop, so the
        // puck settles in the net instead of jittering against the back netting.
        float speed = puckRb.linearVelocity.magnitude;
        if (speed > maxSpeedInNet)
        {
            float newSpeed = Mathf.MoveTowards(speed, maxSpeedInNet, slowdownRate * Time.fixedDeltaTime);
            puckRb.linearVelocity = puckRb.linearVelocity.normalized * newSpeed;
        }
        else if (speed > 0.05f)
        {
            float newSpeed = Mathf.MoveTowards(speed, 0f, slowdownRate * Time.fixedDeltaTime);
            puckRb.linearVelocity = puckRb.linearVelocity.normalized * newSpeed;
        }
        else
        {
            puckRb.linearVelocity = Vector3.zero;
        }

        puckRb.angularVelocity *= 0.95f;
    }

    private void OnDrawGizmos()
    {
        if (GetComponent<Collider>() is BoxCollider box)
        {
            Gizmos.color = new Color(0.3f, 0.6f, 1f, 0.18f); // faint blue = soft netting
            Gizmos.matrix = transform.localToWorldMatrix;
            Gizmos.DrawCube(box.center, box.size);
        }
    }
}
